Portfolio_Voting/Portfolio_Voting/urls.py
from django.contrib import admin
from django.urls import path
from . import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
]

from django.conf.urls import include

urlpatterns += [
    path('portfolios/', include('portfolios.urls', namespace='portfolios')),
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Portfolio_Voting/users/urls.py
from django.urls import path, include
from . import views
from django.conf.urls import url

app_name = 'users'

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('verify/', views.verify, name='verify'),
]

Portfolio_Voting/templates/layout/_navbar.html
{% load static %}
<nav id="sidebar" class="col-2 position-fixed h-100 p-0">
    <ul class="nav flex-column h-100">
        <li>
            <a href="{% url 'portfolios:index' college='文學院' %}" class="nav-link">文學院</a>
        </li>
        <li>
            <a href="{% url 'portfolios:index' college='藝術學院' %}" class="nav-link">藝術學院</a>
        </li>
        <li>
            <a href="{% url 'portfolios:index' college='傳播學院' %}" class="nav-link">傳播學院</a>
        </li>
        <li>
            <a href="{% url 'portfolios:index' college='教育學院' %}" class="nav-link">教育學院</a>
        </li>
        <li>
            <a href="{% url 'portfolios:index' college='醫學院' %}" class="nav-link">醫學院</a>
        </li>
        <li>
            <a href="{% url 'portfolios:index' college='理工學院' %}" class="nav-link">理工學院</a>
        </li>
        <li>
            <a href="{% url 'portfolios:index' college='外國語文學院' %}" class="nav-link">外國語文學院</a>
        </li>
        <li>
            <a href="{% url 'portfolios:index' college='民生學院' %}" class="nav-link">民生學院</a>
        </li>
        <li>
            <a href="{% url 'portfolios:index' college='法律學院' %}" class="nav-link">法律學院</a>
        </li>
        <li>
            <a href="{% url 'portfolios:index' college='社會科學院' %}" class="nav-link">社會科學院</a>
        </li>
        <li>
            <a href="{% url 'portfolios:index' college='管理學院' %}" class="nav-link">管理學院</a>
        </li>
        <li>
            <a href="{% url 'portfolios:index' college='織品服裝學院' %}" class="nav-link">織品服裝學院</a>
        </li>
        <li>
            <a href="{% url 'portfolios:index' college='全人專班-僑生國文' %}" class="nav-link">全人專班-僑生國文</a>
        </li>
    </ul>
</nav>

Portfolio_Voting/templates/layout/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel=icon href="{% static 'logo.png' %}" sizes="16x16" type="image/png">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "vendor/fontawesome/css/all.css" %}">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    {% block custom_head %}{% endblock %}
    {% block meta %}{% endblock %}
    {% block title %}<title>108學年度輔仁大學第一屆國文成果展</title>{% endblock %}
</head>
<body>
    <header class="navbar navbar-expand-md navbar-dark bg-dark fixed-top px-md-5">
        <a class="navbar-brand font-weight-bold mr-auto" href="{% url 'index' %}">
            <img src="{% static 'logo.png' %}" width="30" height="30">
            108學年度輔仁大學第一屆國文成果展
        </a>
        {% if user.is_admin %}
            <span class="text-light mr-3"><i class="far fa-user mr-1"></i>{{ user.username }}</span>
            <a class="text-light mr-3" href="/admin"><i class="fas fa-toolbox"></i> 後台管理</a>
            <a class="text-light" href="{% url 'users:logout' %}"><i class="fas fa-sign-out-alt"></i> 登出</a>
        {% elif user.is_authenticated %}
            <span class="text-light mr-3"><i class="far fa-user mr-1"></i>{{ user.username }}</span>
            <a class="text-light" href="{% url 'users:logout' %}"><i class="fas fa-sign-out-alt"></i> 登出</a>
        {% else %}
            <a class="text-light mr-3" href="{% url 'users:login' %}"><i class="fas fa-sign-in-alt"></i> 登入</a>
        {% endif %}
    </header>
    {% include "./_navbar.html" %}
    <main class="container offset-2 px-5 pt-4">
        {% block content %}{% endblock %}
        <p class="text-center align-text-bottom">訪問人數： {{context_nb_vistors}} 人</p>
    </main>
    {% block custom_script %}{% endblock %}
</body>
</html>