Portfolio_Voting/Portfolio_Voting/urls.py
from django.contrib import admin
from django.urls import path
from . import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
]

from django.conf.urls import include

urlpatterns += [
    path('portfolios/', include('portfolios.urls', namespace='portfolios')),
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Portfolio_Voting/portfolios/urls.py
from django.urls import path
from . import views

app_name = 'portfolios'

urlpatterns = [
    path('<str:college>', views.index, name='index'),
	path('work/<int:portfolio_id>', views.article, name='article'),
	path('work/<int:portfolio_id>/vote/', views.vote, name='vote'),
]

Portfolio_Voting/users/urls.py
from django.urls import path, include
from . import views
from django.conf.urls import url

app_name = 'users'

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('verify/', views.verify, name='verify'),
]

Portfolio_Voting/portfolios/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
MANAGEMENT_CHOICES = (
    ("文學院", "文學院"),
    ("藝術學院", "藝術學院"),
    ("傳播學院", "傳播學院"),
    ("教育學院", "教育學院"),
    ("醫學院", "醫學院"),
    ("理工學院", "理工學院"),
    ("外國語文學院", "外國語文學院"),
    ("民生學院", "民生學院"),
    ("法律學院", "法律學院"),
	("社會科學院", "社會科學院"),
	("管理學院", "管理學院"),
	("織品服裝學院", "織品服裝學院"),
	("全人專班-僑生國文", "全人專班-僑生國文")
)

class Work(models.Model):
	title = models.CharField(max_length=200)
	author = models.CharField(max_length=200)
	work_college = models.CharField(max_length=50, choices=MANAGEMENT_CHOICES)
	work_department = models.CharField(max_length=200)
	description = models.TextField()
	pdf_file = models.FileField(upload_to='pdf_file', blank=True)
	video_url = models.URLField(max_length=200, blank=True)
	created_date = models.DateTimeField(default=timezone.now)

	class Meta:
		ordering = ('-created_date',)

	def __str__(self):
		return self.title

class UserVote(models.Model):
	choice_workTitle = models.ForeignKey("portfolios.Work", on_delete=models.CASCADE)
	studID = models.CharField(max_length=200, unique=True, blank=False)
	
	def __str__(self):
		return self.studID

'''
Work
	title			作品名稱
	author			作者
	work_college	作者之所屬學院
	work_department	作者之所屬系所
	description		作品描述
	pdf_file 		pdf檔案附件
	video_url 		youtube檔案連結
	created_date	發布時間

Choice
	choice_workTitle	被投票的作品名稱
	studID				投票者
	votes				票數
'''

Portfolio_Voting/portfolios/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages

from portfolios.models import Work, UserVote

# Create your views here.
def index(request, college):
	work_list = Work.objects.filter(work_college=college).all()
	StudVoted = len(UserVote.objects.filter(studID=request.user.username).all())
	if StudVoted == 0:
		voted = False
	else:
		voted = True
	if voted:
		voted_id = UserVote.objects.get(studID=request.user.username).choice_workTitle.id
	else:
		voted_id = -1

	context = {
		'work_list': work_list,
		'college': college,
		'voted': voted,
		'voted_id': voted_id
	}
	return render(request, 'portfolios/index.html', context)

def article(request, portfolio_id):
	work = get_object_or_404(Work, pk=portfolio_id)
	StudVoted = len(UserVote.objects.filter(studID=request.user.username).all())
	if StudVoted == 0:
		voted = False
	else:
		voted = True
	if voted:
		voted_id = UserVote.objects.get(studID=request.user.username).choice_workTitle.id
	else:
		voted_id = -1

	return render(request, 'portfolios/article.html', {'work': work, 'voted': voted, 'voted_id': voted_id})

def results(request, choiceText_id):
	work = get_object_or_404(Work, pk=choiceText_id)
	work_vote = UserVote.objects.all().filter(choice_workTitle=work.id)
	work_vote_counting = len(work_vote)

	context = {
		'work': work, 
		'work_vote_counting': work_vote_counting
	}
	return render(request, 'portfolios/article_results.html', context)


def vote(request, portfolio_id):
	if not request.user.is_authenticated:
		messages.add_message(request, messages.WARNING, '請先登入再進行投票')
		return redirect('users:login')

	work = get_object_or_404(Work, pk=portfolio_id)

	StudVoted = len(UserVote.objects.filter(studID=request.user.username).all())
	if StudVoted == 0:
		Stud_Voting = UserVote.objects.create(
			choice_workTitle=Work.objects.filter(pk=work.id).get(),
			studID=request.user.username
		)
		Stud_Voting.save()
		return HttpResponseRedirect(request.GET.get('next'))
	else:
		messages.add_message(request, messages.WARNING, '您已經投過票了喔!')
		return HttpResponseRedirect(request.GET.get('next'))

Portfolio_Voting/templates/portfolios/article.html
{% extends "layout/base.html" %}

{% block content %}
{% if messages %}
    {% for message in messages %}
    <div class="alert alert-warning {% if message.tags %} alert-{{ message.tags }} {% endif %} alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% endfor %}
{% endif %}
<div class="py-3 m-0 mb-4">
    <div class="d-flex flex-column">
        <div class="d-flex align-items-center mb-2">
            <h2 class="card-title m-0 mr-4">{{ work.title }}</h2>
            <span class="mr-3">{% if work.id == voted_id %}<i class="fas fa-heart"></i>{% else %}<i class="far fa-heart"></i>{% endif %} {{ work.uservote_set.all | length }}</span>
            <a href="{% url 'portfolios:vote' work.id %}?next={% url 'portfolios:article' work.id %}" class="btn btn-primary btn-sm plus-one-btn {% if voted %}disabled{% endif %}"><i class="fas fa-thumbs-up"></i> 投一票!</a>
            <!-- <a href="{% url 'portfolios:vote' work.id %}?next={% url 'portfolios:article' work.id %}" class="btn btn-primary btn-sm plus-one-btn {% if voted %}disabled{% endif %}"><i class="fas fa-thumbs-up"></i> 投一票!</a> -->
        </div>
        <p class="card-text">
            {{ work.work_department }} <br/> 
            {{ work.author }}
        </p>
        <h4>作品簡介</h4>
        <p class="text-muted">
            {{ work.description }}
        </p>
        <h4>作品內容</h4>
        {% if work.pdf_file %}
            <iframe src="{{ MEDIA_URL }}{{ work.pdf_file }}#toolbar=0" width="100%" height="700px"></iframe>
        {% elif work.video_url %}
            <div id="video"></div>
            <script>
                $(document).ready(function() {
                    const regExp = /^.*(youtu.be\/|v\/|u\/\w\/|embed\/|watch\?v=|&v=)([^#&?]*).*/;
                    const match = '{{ work.video_url }}'.match(regExp);
            
                    let videoId = null;
                    if (match && match[2].length === 11) {
                        videoId = match[2];
                    }

                    if (videoId) {
                        const iframeMarkup = '<iframe width="560" height="315" src="//www.youtube.com/embed/' 
                                                + videoId + '" frameborder="0" allowfullscreen></iframe>';
                        $('#video').append(iframeMarkup);
                    } else {
                        $('#video').append('<p>影片連結失效</p>');
                    }
                })
            </script>
        {% else %}
            <p>尚未提供作品資料</p>
        {% endif %}
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="confirmModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
            <h5 class="modal-title">是否要投票？</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            </div>
            <div class="modal-body">
                <p>確定要投給這個作品？</p>
                <p class="font-weight-bold">注意：投票後不可更改</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">關閉</button>
                <a id="confirmBtn" href="#" class="btn btn-primary">確定</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block custom_script %}
<script>
    $('.plus-one-btn').click(function(event) {
        event.preventDefault();
        $('#confirmModal').modal('show');
        $('#confirmBtn').attr('href', this.href);
    });
</script>
{% endblock %}

Portfolio_Voting/templates/portfolios/index.html
{% extends "layout/base.html" %}

{% block content %}
{% if messages %}
    {% for message in messages %}
    <div class="alert alert-warning {% if message.tags %} alert-{{ message.tags }} {% endif %} alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    {% endfor %}
{% endif %}
<h2 class="font-weight-bold header-sm">{{ college }}</h2>
<p class="text-muted">為您喜愛的作品投下神聖的一票!</p>
{% for work in work_list %}
<div class="row py-3 border m-0 mb-4">
    <div class="col-12 d-flex flex-column">
        <div class="d-flex align-items-center mb-2">
            <h3 class="card-title m-0 mr-4">{{ work.title }}</h3>
            <span class="mr-3">{% if work.id == voted_id %}<i class="fas fa-heart"></i>{% else %}<i class="far fa-heart"></i>{% endif %} {{ work.uservote_set.all | length }}</span>
            <a href="{% url 'portfolios:vote' work.id %}?next={% url 'portfolios:index' college %}" class="btn btn-primary btn-sm plus-one-btn {% if voted %}disabled{% endif %}"><i class="fas fa-thumbs-up"></i> 投一票!</a>
        </div>
        <p class="card-text">
            {{ work.work_department }} <br/> 
            {{ work.author }}
        </p>
        <p class="text-muted">
            {{ work.description|truncatechars:150 }}
        </p>
        <a href="{% url 'portfolios:article' work.id %}" class="btn btn-secondary align-self-end mt-auto">觀看作品</a>
    </div>
</div>
{% endfor %}

<!-- Modal -->
<div class="modal fade" id="confirmModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
            <h5 class="modal-title">是否要投票？</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            </div>
            <div class="modal-body">
                <p>確定要投給這個作品？</p>
                <p class="font-weight-bold">注意：投票後不可更改</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">關閉</button>
                <a id="confirmBtn" href="#" class="btn btn-primary">確定</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block custom_script %}
<script>
    $('.plus-one-btn').click(function(event) {
        event.preventDefault();
        $('#confirmModal').modal('show');
        $('#confirmBtn').attr('href', this.href);
    });
</script>
{% endblock %}